### ISSUE TITLE
What is this classifying?

### ISSUE THREAD

**Issue by chessai** [ocramz/cmbnt-test#1]
I understand FDA/QDA, but I'm not sure what this is classifying (haven't read through the code enough). what does a result of true/false mean?

**Comment by chessai** [comment]
Going to read more shortly

**Comment by ocramz** [comment]
Oh, the Bool there is just a way to encode the two outcomes of a binary classifier. Don't pay much attention to this, it's my solution to a coding test for a job application and was mostly built over a weekend (got the job btw) :)

**Comment by chessai** [comment]
Oh ok, I couldn't really see much structure anywhere and was wondering if I missed something. Where are you working now? Good job!

**Comment by ocramz** [comment]
@chessai briefly, the classifiers are called by REST endpoints defined in a Scotty server: https://github.com/ocramz/cmbnt-test/blob/master/app/Main.hs#L60 I'd like to blog a bit in detail about this whole project sometime soon ..

**Comment by chessai** [comment]
Oh yeah, I could tell that. I had it running and was playing around with
it. I made some changes (like training with qda/fda up front and caching
the resulting classifiers/distanceMin/sample data), so that we saw much
more speedup. The graph was a really nice touch. Do you recommend vega or
was it just something you could spin up quickly?
